title: Configuration
# description: Nuxt is configured with sensible defaults to make you productive.
description: Windows is configured with sensible defaults to make you productive.
navigation.icon: i-lucide-cog